monorepo_root = true

[monorepo]
config_roots = ["adapters/emacs", "renderer"]
lockfile = false

[tasks.setup]
description = "Install renderer dependencies"
run = [
  "mise //renderer:setup",
]

[tasks.check]
description = "Check the renderer"
run = [
  "mise //renderer:check",
]
